language: objective-c
osx_image: xcode7.1

install:
  - gem install xcpretty

script:
  - set -o pipefail && xcodebuild -workspace ReactiveKit.xcworkspace -scheme ReactiveKit-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0' test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)
