language: objective-c
osx_image: xcode8

script:
  - xcodebuild -workspace ReactiveKit.xcworkspace -scheme ReactiveKit-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' test
